### ISSUE TITLE
変換後のルールのチャンネルに WinEventLog: という記載がある

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa-rules#44]
## 対象バージョン

571eee894bb3e224cb7f7c8af2e2fdce498f7bb7

## 内容

logsourceのserviceがbits-clientだとChannelが「WinEventlog:Microsoft-Windows-Bits-Client/Operational」という記載が出てきて、 https://answers.microsoft.com/en-us/windows/forum/all/unknown-events-in-windowsbits-clientoperational/c0856f82-44a2-4998-9a3b-9d6eda328136 のようなXMLを確認したらChannelの要素は「Microsoft-Windows-Bits-Client/Operational」となっているため検知しない可能性がある。

hayabusa-rules • sigma\builtin\bits_client\win_bits_client_susp_local_file.yml:
  10    SELECTION_1:
  11:     Channel: WinEventlog:Microsoft-Windows-Bits-Client/Operational
  12    SELECTION_2:

hayabusa-rules • sigma\builtin\bits_client\win_bits_client_susp_powershell_job.yml:
  10    SELECTION_1:
  11:     Channel: WinEventlog:Microsoft-Windows-Bits-Client/Operational
  12    SELECTION_2:

hayabusa-rules • sigma\builtin\bits_client\win_bits_client_susp_use_bitsadmin.yml:
  10    SELECTION_1:
  11:     Channel: WinEventlog:Microsoft-Windows-Bits-Client/Operational
  12    SELECTION_2:

## 期待する挙動

logsourceが以下の状態のときにはChannelは「Microsoft-Windows-Bits-Client/Operational」になるように変換する。

```yaml
logsource:
  product: windows
  service: bits-client

```

**Comment by hitenkoku** [comment]
sigmaのgeneric/windows-service.ymlが原因。sigmaのレポジトリに修正をかけるように対応する。

```yaml
    windows-bits-client:
        product: windows
        service: bits-client
        conditions:
            Channel: 'WinEventlog:Microsoft-Windows-Bits-Client/Operational'
```
