### ISSUE TITLE
[bug] The order of the list of values ​​in the `windash` modifier is different every time `logsource_mapping.py` is executed

### ISSUE THREAD

**Issue by fukusuket** [Yamato-Security/hayabusa-rules#635]
The order of the list of values ​​in the windash modifier is different every time logsource_mapping.py is executed.
If the original rules are unchanged, the expected behavior is that the transformed rules will be the same.

##### First time logsource_mapping.py result
```yaml
title: Wlrmdr.EXE Uncommon Argument Or Child Process
id: d6a74c59-8fd1-7d1f-4448-5dbe0aff0bdb
related:
    - id: 9cfc00b6-bfb7-49ce-9781-ef78503154bb
      type: derived
status: test
description: |
    Detects the execution of "Wlrmdr.exe" with the "-u" command line flag which allows anything passed to it to be an argument of the ShellExecute API, which would allow an attacker to execute arbitrary binaries.
    This detection also focuses on any uncommon child processes spawned from "Wlrmdr.exe" as a supplement for those that posses "ParentImage" telemetry.
references:
    - https://twitter.com/0gtweet/status/1493963591745220608?s=20&t=xUg9DsZhJy1q9bPTUWgeIQ
    - https://lolbas-project.github.io/lolbas/Binaries/Wlrmdr/
author: frack113, manasmbellani
date: 2022/02/16
modified: 2024/03/06
tags:
    - attack.defense_evasion
    - attack.t1218
    - sysmon
logsource:
    category: process_creation
    product: windows
detection:
    process_creation:
        EventID: 1
        Channel: Microsoft-Windows-Sysmon/Operational
    selection_parent: # This selection is looking for processes spawned from wlrmdr using the "-u" flag
        ParentImage|endswith: \wlrmdr.exe
    selection_child_img:
        - Image|endswith: \wlrmdr.exe
        - OriginalFileName: WLRMNDR.EXE
    selection_child_cli:
        CommandLine|contains|all:
            - '-a '
            - '-f '
            - '-m '
            - '-s '
            - '-t '
            - '-u '
            - '/a '
            - '/f '
            - '/m '
            - '/s '
            - '/t '
            - '/u '
    filter_main_winlogon:
        ParentImage: C:\Windows\System32\winlogon.exe
    filter_main_empty:
        ParentImage:
            - ''
            - '-'
    filter_main_null:
        ParentImage: null
    condition: process_creation and (selection_parent or (all of selection_child_* and not 1 of filter_main_*))
falsepositives:
    - Unknown
level: medium
ruletype: Sigma
```
##### Second time logsource_mapping.py result
`CommandLine|contains|all` 's list order is differ.
```yaml
title: Wlrmdr.EXE Uncommon Argument Or Child Process
id: d6a74c59-8fd1-7d1f-4448-5dbe0aff0bdb
related:
    - id: 9cfc00b6-bfb7-49ce-9781-ef78503154bb
      type: derived
status: test
description: |
    Detects the execution of "Wlrmdr.exe" with the "-u" command line flag which allows anything passed to it to be an argument of the ShellExecute API, which would allow an attacker to execute arbitrary binaries.
    This detection also focuses on any uncommon child processes spawned from "Wlrmdr.exe" as a supplement for those that posses "ParentImage" telemetry.
references:
    - https://twitter.com/0gtweet/status/1493963591745220608?s=20&t=xUg9DsZhJy1q9bPTUWgeIQ
    - https://lolbas-project.github.io/lolbas/Binaries/Wlrmdr/
author: frack113, manasmbellani
date: 2022/02/16
modified: 2024/03/06
tags:
    - attack.defense_evasion
    - attack.t1218
    - sysmon
logsource:
    category: process_creation
    product: windows
detection:
    process_creation:
        EventID: 1
        Channel: Microsoft-Windows-Sysmon/Operational
    selection_parent: # This selection is looking for processes spawned from wlrmdr using the "-u" flag
        ParentImage|endswith: \wlrmdr.exe
    selection_child_img:
        - Image|endswith: \wlrmdr.exe
        - OriginalFileName: WLRMNDR.EXE
    selection_child_cli:
        CommandLine|contains|all:
            - '-a '
            - '-f '
            - '/t '
            - '-u '
            - '/a '
            - '-m '
            - '/u '
            - '-s '
            - '/s '
            - '-t '
            - '/m '
            - '/f '
    filter_main_winlogon:
        ParentImage: C:\Windows\System32\winlogon.exe
    filter_main_empty:
        ParentImage:
            - ''
            - '-'
    filter_main_null:
        ParentImage: null
    condition: process_creation and (selection_parent or (all of selection_child_* and not 1 of filter_main_*))
falsepositives:
    - Unknown
level: medium
ruletype: Sigma
```
