### ISSUE TITLE
Conversion error:  Backend does not support map values of type <class 'bool'>

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa-rules#85]
`rules/windows/driver_load/driver_load_vuln_avast_anti_rootkit_driver.yml`と
`rules/windows/network_connection/net_connection_win_remote_powershell_session_network.yml`は以下のエラーで変換できません：
`Backend does not support map values of type <class 'bool'>`

`driver_load_vuln_avast_anti_rootkit_driver.yml`:
```
logsource:
    product: windows
    category: driver_load
detection:
    selection_sysmon:
        Hashes|contains:
            - 'MD5=a179c4093d05a3e1ee73f6ff07f994aa'
            - 'SHA1=5d6b9e80e12bfc595d4d26f6afb099b3cb471dd4'
            - 'SHA256=4b5229b3250c8c08b98cb710d6c056144271de099a57ae09f5d2097fc41bd4f1'
    selection_other:
        - MD5: 'a179c4093d05a3e1ee73f6ff07f994aa'
        - SHA1: '5d6b9e80e12bfc595d4d26f6afb099b3cb471dd4'
        - SHA256: '4b5229b3250c8c08b98cb710d6c056144271de099a57ae09f5d2097fc41bd4f1'
    driver_img:
        ImageLoaded|endswith: '\aswArPot.sys'
    driver_status:
        - Signed: false
        - SignatureStatus: Expired
    condition: 1 of selection* or all of driver_*
```

`net_connection_win_remote_powershell_session_network.yml`:
```
logsource:
  category: network_connection
  product: windows
detection:
  selection:
    DestinationPort:
      - 5985
      - 5986
    Initiated: true  # only matches of the initiating system can be evaluated
  filter:
    - User|contains: # covers many language settings for Network Service, please expand
      - 'NETWORK SERVICE'
      - 'NETZWERKDIENST'
      - 'SERVIZIO DI RETE'
      - 'SERVICIO DE RED'
    - User|contains|all:
        - 'SERVICE R'
        - 'SEAU'
    - SourceIp|startswith: '0:0:'
  condition: selection and not filter
```
