### ISSUE TITLE
変換された"Code Integrity Blocked Driver Load"ルールはパースエラーを起こす

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa-rules#9]
スキャン時のエラー：
```
[WARN] Failed to parse rule file. (FilePath : ../hayabusa-rules/sigma/builtin/code_integrity/win_codeintegrity_failed_driver_load.yml)
[WARN] There is no selection node under detection.
```

**元々のルール(https://github.com/SigmaHQ/sigma/blob/master/rules/windows/builtin/code_integrity/win_codeintegrity_failed_driver_load.yml):**
```
title: Code Integrity Blocked Driver Load
id: f8931561-97f5-4c46-907f-0a4a592e47a7
description: Detects driver load events that got blocked by Windows code integrity checks
author: Florian Roth
status: experimental
references:
    - https://twitter.com/SBousseaden/status/1483810148602814466
date: 2022/01/20
tags:
    - attack.execution
logsource:
    product: windows
    service: codeintegrity-operational
detection:
    keywords:
        - 'that did not meet the Microsoft signing level requirements'
    condition: keywords
falsepositives:
    - Unknown
level: high
```

**変換されたルール:**
```
title: Code Integrity Blocked Driver Load
ruletype: Sigma
author: Florian Roth
date: 2022/01/20
description: Detects driver load events that got blocked by Windows code integrity
  checks
detection:
  condition: that did not meet the Microsoft signing level requirements
falsepositives:
- Unknown
id: f8931561-97f5-4c46-907f-0a4a592e47a7
level: high
logsource:
  product: windows
  service: codeintegrity-operational
references:
- https://twitter.com/SBousseaden/status/1483810148602814466
status: experimental
tags:
- attack.execution
```
